checkoutHandler:
  handler: src/handlers/checkoutHandler.checkoutHandler
  events:
    - http:
        path: /api/checkout
        method: post

statusHandler:
  handler: src/handlers/statusHandler.statusHandler
  events: 
    - http:
        path: /api/status
        method: get