stages:
  - dev
  - prod
  - surge
topics:
  alarm:
    topic: ${self:service}-${self:provider.stage}-alerts-alarm
externalStack: true
dashboards: true
definitions:
  functionErrors:
    namespace: "AWS/Lambda"
    actionsEnabled: true
    metric: Errors # define custom metrics here
    threshold: 5
    statistic: Sum
    period: 60
    evaluationPeriods: 5
    datapointsToAlarm: 3
    comparisonOperator: GreaterThanOrEqualToThreshold
  functionThrottles:
    namespace: "AWS/Lambda"
    actionsEnabled: true
    metric: Throttles # define custom metrics here
    threshold: 10
    statistic: Sum
    period: 60
    evaluationPeriods: 5
    datapointsToAlarm: 1
    comparisonOperator: GreaterThanOrEqualToThreshold
  functionDuration:
    namespace: "AWS/Lambda"
    actionsEnabled: true
    metric: Duration # define custom metrics here
    threshold: 10000
    statistic: Maximum
    period: 60
    evaluationPeriods: 5
    datapointsToAlarm: 1
    comparisonOperator: GreaterThanOrEqualToThreshold
alarms:
  - functionErrors
  - functionThrottles
  - functionDuration